version: '3.1'
# Default ${APP_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - WebApp data directory
# ./server-logs - placeholder for webserver logs

networks:
  webservice:
    name: shared-web
    external: true


services:
  # nginx-app:
  #   container_name: nginx-app
  #   image: nginxdemos/hello
  #   ports:
  #     - 81:80
  #   networks: 
  #     - webservice

  db:
    container_name: postgres-db
    image: postgres:15.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./docker_data_postgresql:/var/lib/postgresql/data
      - ./docker_data_postgresql_dropbox:/windows_dropbox
    ports:
      - 5432:5432
    networks: 
      - webservice

  # ubuntu:
  #   container_name: ubuntu-image
  #   image: ubuntu:latest
  #   stdin_open: true
  #   tty: true
  #   user: root
  #   ports:
  #     - 80:8111
  #   volumes:
  #     - ./docker_data_ubuntu:/docker_data_ubuntu/
  #   networks: 
  #     - webservice
